name: sociabile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"  # Adjusted this line to be compatible with 3.1.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  awesome_snackbar_content: ^0.1.3
  google_sign_in: ^6.1.4
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
